### PR TITLE
ci: replace existing services with GitHub Actions

### PR DESCRIPTION
**Pull request by erisu**
### Motivation, Context & Description

- Use GitHub Actions Workflow
- Added `nyc` code coverage to match other repo GitHub Actions Workflow
- Drop Travis CI
- Drop AppVeyor
- Commit `package-lock.json` to use `npm cit`
- Add GitHub Actions Workflow status badge to README

### Testing

- `npm t`
- Review GitHub Actions Test Run

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by timbru31** [comment]
Ref to https://github.com/apache/cordova/issues/4

**Comment by timbru31** [comment]
I assume you need to rebuild the lockfile since #28 was merged :)

**Comment by erisu** [comment]
Not until #27 is merged.

**Comment by erisu** [comment]
rebased and ready for review.

**Pull request merged**
